bagrinsergiu/Sylius

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Channel.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ChannelPricing.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Product.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductTranslation.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductVariant.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ChannelPricing.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Product.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductImage.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductVariant.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductVariantTranslation.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/filters.xml

| Q  | A |
| Related tickets | https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/1, https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/2, https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/3, https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/4 |
| Tests | N |
* Updated: Products Endpoints and Serialization, as well as any product related resources

Product endpoints

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Channel.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Promotion.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/PromotionAction.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/PromotionRule.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Promotion.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/PromotionAction.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/PromotionRule.xml

| Q  | A |
| Related tickets | https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/11, https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/12, https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/13, https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/14 |
| Tests | N |
* New: "PromotionActions" and "PromotionRules" endpoints, and serialization.
* Update: Promotion endpoint and serialization.

Discount endpoints

---

.gitignore
config/packages/lexik_jwt_authentication.yaml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/GatewayConfig.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/PaymentMethod.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/GatewayConfig.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/PaymentMethod.xml

| Q  | A |
| Related tickets | https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/19, https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/20 |
| Tests |  N |
* Update: Payment method endpoints

Payment methods endpoints

---

src/Sylius/Bundle/ApiBundle/Applicator/PaymentStateMachineTransitionApplicator.php
src/Sylius/Bundle/ApiBundle/Applicator/PaymentStateMachineTransitionApplicatorInterface.php
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Country.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Payment.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingMethod.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Country.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Customer.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Order.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/OrderItem.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Promotion.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Shipment.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ShippingMethod.xml

| Q  | A |
| Related tickets | https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/9, https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/10 |
| Tests | N |
* Update: Order endpoints.

Order endpoints

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/PromotionAction.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/PromotionRule.xml

| Q  | A |
| Tests | N |
* Updated: Promotion endpoints.

small changes

---

composer.json
package-lock.json
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Currency.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Currency.xml

| Q  | A |
| Related tickets | https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/33, https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/35, https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/36, https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/37, https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/38 |
| Tests | N |
* Update: Small config changes

ExchangeRatesCRUD added

---

src/Sylius/Bundle/AddressingBundle/Resources/config/doctrine/model/Zone.orm.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingMethod.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingMethodRule.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Zone.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ShippingMethod.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ShippingMethodRule.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Zone.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ZoneMember.xml
src/Sylius/Component/Addressing/Model/Zone.php
src/Sylius/Component/Addressing/Model/ZoneInterface.php

| Q  | A |
| Related tickets | https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/21, https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/22, https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/26 |
| Tests | N |
* Update: Updated shipping method and zone endpoints

shipping method and zone endpoints changes

---

src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ShippingMethod.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ShippingMethodTranslation.xml

| Q  | A |
| Related tickets | N |
| Tests | N |
* Fixed: Small fixes

small fixes

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/OrderItem.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Order.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/OrderItem.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Product.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductVariant.xml

| Q  | A |
| Tests | N |
* Improved: Added normalization context for Order > OrderItem subresource

Added normalization group to OrderItem subresource

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Shipment.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingMethod.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Order.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Shipment.xml

| Q  | A |
| Tests | N |
* Improved: Order>Shipment endpoint

improved shippment endpoint

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Product.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductVariant.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ChannelPricing.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductVariant.xml

| Q  | A |
| Related tickets | https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/87 |
| Tests | N |
* Improved: Product Variants endpoints

improved product variants endpoint

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Taxon.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Taxon.xml

| Q  | A |
| Tests | N |
* Improved: Added name field to taxon endpoints

added name to taxon endpoint

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Taxon.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Taxon.xml

Reverts bagrinsergiu/Sylius#21

Revert "added name to taxon endpoint"

---

src/Sylius/Bundle/ApiBundle/DataProvider/InventoryCollectionDataProvider.php
src/Sylius/Bundle/ApiBundle/DataProvider/InventoryItemDataProvider.php
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Product.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductVariant.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ChannelPricing.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Product.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductImage.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductTranslation.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductVariant.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductVariantTranslation.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/data_providers.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/filters.xml
src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductVariantRepository.php
src/Sylius/Component/Core/Repository/ProductVariantRepositoryInterface.php

| Q  | A |
| Related tickets | https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/1, https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/2, https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/3, https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/76, https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/87, https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/97, https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/98, https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/100, https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/101,  |
| Tests | N |
* New: Separated Inventory …

Overall Product improvement

---

src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductVariantTranslation.xml

| Q  | A |
| Tests | N |
* Updated: Added a previously missed commit

missed fix

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Customer.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Customer.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/CustomerGroup.xml

| Q  | A |
| Related tickets | https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/107 |
| Tests | N |
* Updated: Added Group to Customer response/request

customer improvement

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductVariant.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductVariant.xml

| Q  | A |
| Tests | N |
* Improved: Added enabled field to product-variants

added enabled field to variant

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductOption.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductOptionValueTranslation.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductOption.xml

| Q  | A |
| Related tickets | https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/113 |
| Tests | N |
* Updated: Prepared product option endpoints

product options

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductOptionValue.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductVariant.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Product.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductOption.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductOptionValue.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductVariant.xml

| Q  | A |
| Related tickets | https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/113 |
| Tests | N |
* Updated: Prepared product option endpoints

product improvements

---

src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Customer.xml

| Q  | A |
| Tests | N |
* Updated: Now we can see defaultAdress field on customer response

Address improvement

---

src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductOptionValue.xml

| Q  | A |
| Tests | N |
* Fixed: ProductOptionValue value can no longer be updated by value field.

product option fix

---

src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ChannelPricing.xml

| Q  | A |
| Tests |  N |
* Fixed: Added originalPrice to shop product endpoints

Added originalPrice to shop product endpoints

---

.env
composer.json
config/bundles.php
config/packages/nelmio_cors.yaml
symfony.lock

Added nelmio/cors package for cross origin support.

Added cors

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/PromotionCoupon.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/PromotionCoupon.xml

| Q  | A |
| Related tickets | https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/132 |
| Tests | N |
* New: Added Promotion Coupon endpoints

Promotion coupons

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/PromotionCoupon.xml

Promontion Coupon identifier is ID now

Changed PromotionCoupon identifier

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/TaxRate.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/TaxRate.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/filters.xml
symfony.lock

| Q  | A |
| Related tickets | bagrinsergiu/brizy-cloud-sylius-demo-template/issues/140|
| Tests | N |
* New: Added Endpoints and Zone filter for TaxRates

Add TaxRates endpoints and filter

---

src/Sylius/Bundle/ApiBundle/Resources/config/serialization/TaxRate.xml

| Q  | A |
| Tests | N |
* Fixed: Added 'code' to TaxRate creation endpoint

Added 'code'

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/PromotionAction.xml

| Q  | A |
| Related tickets | bagrinsergiu/brizy-cloud-sylius-demo-template/issues/144 |
| Tests |  N |
* New: Added schema example for Actions->Configurations in Promotion

Modified Promotion schema for actions

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/PromotionAction.xml

| Q  | A |
| Related tickets | bagrinsergiu/brizy-cloud-sylius-demo-template/issues/144 |
| Tests | N |
* Fixed: Fixed typos

Fixed typo

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductOptionValue.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductOptionValue.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductOptionValueTranslation.xml

**related issues**
- https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/157;
- https://github.com/bagrinsergiu/brizy-cms-ui/issues/1937
**modifications:**
Added endpoint for creating ProductOptionValues

Add endpoint for creating product_option_values

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Province.xml

**related issues:**
- https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/160
- https://github.com/bagrinsergiu/brizy-cms-ui/issues/2003
**modifications:**
Add endpoint for getting all provinces

Add endpoint for getting all provinces

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/GatewayConfig.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/GatewayConfig.xml
symfony.lock

**related issues:** 
- https://github.com/bagrinsergiu/brizy-cms-ui/issues/1931
- https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/155
**modifications:**
*add `factory_name` and `gateway_name` fields to `api/v2/admin/gateway-config/{id}` endpoint*

added factory_name and gateway_name fields to admin:get:GatewayConfig

---

config/packages/_sylius.yaml
src/Sylius/Bundle/ApiBundle/DataProvider/Helpers/ProductDataProviderHelper.php
src/Sylius/Bundle/ApiBundle/DataProvider/ProductCollectionDataProvider.php
src/Sylius/Bundle/ApiBundle/DataProvider/ProductItemDataProvider.php
src/Sylius/Bundle/ApiBundle/Entity/Product/Product.php
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Product.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services.xml

`onHand` - is calculated by summing `onHand` of `product-variants`
`price` -  is set as the price of first variant
Fields are available for admin:product:read group

Add onHand and price fields to product

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Taxon.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Taxon.xml

Fixed admin Taxon creation/updating endpoints
Note: the `parent` property is optional
Related Issues:
- https://github.com/bagrinsergiu/brizy-cloud-sylius-demo-template/issues/169
- https://github.com/bagrinsergiu/brizy-cms-ui/issues/2155

Fixed Taxon create/update

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Product.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductTranslation.xml

Fixed updating product translations
Linked Issues:
- bagrinsergiu/brizy-cms-ui/issues/2121
- bagrinsergiu/brizy-cloud-sylius-demo-template/issues/163

fixed updating product translations
